import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/navbar";

export const metadata: Metadata = {
  title: "Carolls",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        <main className="container mx-auto px-5 pt-10">{children}</main>
      </body>
    </html>
  );
}
